himkt/konoha

.travis.yml
Dockerfile
Makefile
README.md
data/download_spm.sh
requirements.txt
setup.py
tests/test_word_tokenize.py
tiny_tokenizer/word_tokenizer.py

Support character based/sub-word based tokenizers.

Support Character and Sentencepiece tokenizer

---

.travis.yml
README.md
example/tokenize_demo.py
setup.py
tests/test_word_tokenize.py
tiny_tokenizer/__init__.py
tiny_tokenizer/word_tokenizer.py

Add the support [WorksApplications/SudachiPy](https://github.com/WorksApplications/SudachiPy) as a tokenizer.

Support Sudachi tokenizer

---

example/tokenize_demo.py
tiny_tokenizer/word_tokenizer.py

Add some docstring and update the example.
Need to be merged after #22.

Add docstring

---

tiny_tokenizer/tiny_tokenizer_token.py

related to #29
This PR introduce a new attribute `postag2` to `Token` class.

Add attribute postag2 to Token

---

.travis.yml
setup.py

It's only a propal but how about using `extras_require` to separate package dependencies.
See.
https://qiita.com/ledmonster/items/74886ac2f51fb2e5fd64

use extras_require

---

example/tokenize_demo.py
setup.py
tests/word_tokenizer/test_segmentation.py
tiny_tokenizer/__init__.py
tiny_tokenizer/word_tokenizer.py
tiny_tokenizer/word_tokenizers/__init__.py
tiny_tokenizer/word_tokenizers/whitespace_tokenizer.py

I introduce whitespace tokenizer to tiny_tokenizer.
```python
In [1]: from tiny_tokenizer import WordTokenizer
In [2]: tk = WordTokenizer("whitespace")
In [3]: tk.tokenize("わたし は 猫")
Out[3]: [私, は, 猫]
```

Add whitespace tokenizer

---

tiny_tokenizer/word_tokenizers/mecab_tokenizer.py

https://github.com/buruzaemon/natto-py/issues/114

[Hotfix] Remove whitespace at end of parse result with MeCab

---

poetry.lock
pyproject.toml
setup.py
tests/word_tokenizer/test_postagging.py
tests/word_tokenizer/test_segmentation.py
tiny_tokenizer/__init__.py
tiny_tokenizer/word_tokenizer.py
tiny_tokenizer/word_tokenizers/__init__.py
tiny_tokenizer/word_tokenizers/janome_tokenizer.py

This PR introduces the support of Janome tokenizer.
https://mocobeta.github.io/janome/en/

Support janome

---

.github/workflows/pythonpackage.yml
README.md
example/tokenize_demo.py
poetry.lock
pyproject.toml
tests/word_tokenizer/test_segmentation_with_remote.py
tiny_tokenizer/resource.py
tiny_tokenizer/word_tokenizer.py

This PR introduces a `s3` support for a dictionary or a model.
```python
from tiny_tokenizer import WordTokenizer
if __name__ == "__main__":
sentence = "首都大学東京"
word_tokenizer = WordTokenizer("mecab")
print(word_tokenizer.tokenize(sentence))
word_tokenizer = WordTokenizer("mecab", user_dictionary_path="s3://abc/xxx.dic")
print(word_tokenizer.tokenize(sentence))
word_tokenizer = WordTokenizer("mecab", system_dictionary_path="s3://abc/yyy")
print(word_tokenizer.tokenize(sentence))
word_tokenizer = WordTokenizer("sentencepiece", model_path="s3://abc/zzz.model")
print(word_tokenizer.tokenize(sentence))
```

Support remote

---

konoha/word_tokenizer.py
konoha/word_tokenizers/mecab_tokenizer.py

Extract a method to parse output string from MeCab

---

konoha/konoha_token.py
konoha/word_tokenizer.py
konoha/word_tokenizers/janome_tokenizer.py

https://www.python.org/dev/peps/pep-0008/#indentation

Follow PEP8 indentation rule

---

konoha/resource.py
konoha/word_tokenizer.py
konoha/word_tokenizers/janome_tokenizer.py
konoha/word_tokenizers/kytea_tokenizer.py
konoha/word_tokenizers/mecab_tokenizer.py
konoha/word_tokenizers/sentencepiece_tokenizer.py
konoha/word_tokenizers/sudachi_tokenizer.py
konoha/word_tokenizers/tokenizer.py

Simple code-fix and modify error messages.

---

README.md

Thank you for making this handy library.
I found a tiny typo in README.md, nothing critical.
I hope this pr helps others to use konoha smoothly.

Very small fix on README.md

---

poetry.lock
pyproject.toml

In this PR, I replace allennlp v0.9.0 with v1.0.0.

Update AllenNLP to v1.

---

docs/source/installation.rst

Fix `installation.rst` from `Optuna` to `Konoha`.

Fix installation.rst

---

pyproject.toml

This helps license checker tools to work a bit better.

Add license metadata

---

README.md

Update README to add description of breaking change

---

konoha/api/server.py
konoha/api/v1/tokenization.py

For storing objects, it may be recommended to use `app.state` provided by `starlette`.
(ref. https://www.starlette.io/applications/)

Use `app.state` for caching objects

---

konoha/word_tokenizers/character_tokenizer.py
konoha/word_tokenizers/janome_tokenizer.py
konoha/word_tokenizers/kytea_tokenizer.py
konoha/word_tokenizers/mecab_tokenizer.py
konoha/word_tokenizers/nagisa_tokenizer.py
konoha/word_tokenizers/sentencepiece_tokenizer.py
konoha/word_tokenizers/sudachi_tokenizer.py
konoha/word_tokenizers/tokenizer.py
konoha/word_tokenizers/whitespace_tokenizer.py

This PR makes word tokenizers clean.

Refactoring: cleanup word_tokenizers

---

README.md

This PR adds a colab badge to README.

Add colab badge

---

konoha/word_tokenizers/mecab_tokenizer.py
tests/word_tokenizer/test_mecab_tokenizer.py

Thank you for this awesome library! 🙏 
Purpose of this PR is to use MeCabTokenizer with [UniDic format](https://unidic.ninjal.ac.jp/faq) dictionaries.

Support UniDic format for MeCabTokenizer

---

konoha/word_tokenizer.py

This PR changes the semantics of `endpoint` in `WordTokenizer`.
```python
from konoha import WordTokenizer
tokenizer = WordTokenizer(tokenizer="mecab", endpoint="http://localhost:8000/api/v1/tokenize")
tokenizer.tokenize("私は猫です")
```
After merging this PR, you have to specify the **base url** of API server.
```python
from konoha import WordTokenizer
tokenizer = WordTokenizer(tokenizer="mecab", endpoint="http://localhost:8000")
tokenizer.tokenize("私は猫です")
tokenizer.batch_tokenize(["私は猫です", "あなたは？"])
```

Change way to receive endpoint

---

poetry.lock
pyproject.toml

Some packages are not necessary as default.

Make rich and requests optional

---

docker/app/Dockerfile
docker/dev/Dockerfile

ref/ `python-poetry/poetry/issues/4511`

Fix poetry/setuptools version in Dockerfiles

---

poetry.lock
pyproject.toml

🔗  https://github.com/himkt/konoha/pull/154

Bump fastapi from 0.54.2 to 0.65.2

---

.github/workflows/ci.yml
README.md
docs/source/installation.rst
example/Konoha_Example.ipynb

This PR prepares to change the default branch from `master` to `main`.

Rename master to main

---

poetry.lock
pyproject.toml

Relax importlib-metadata constraint

---

Dockerfile

I changed the layout in https://github.com/himkt/konoha/pull/193 but forgot to follow in Dockerfile.

fix: copy src folder

---

poetry.lock

For https://cwe.mitre.org/data/definitions/400.html.

deps: upgrade fastapi to resolve starlette issue
