- tests/test_word_tokenize.py
- tiny_tokenizer/word_tokenizer.py
In this PR, I update WordTokenizer so that it accepts lowercased names of tokenizers.
(For example, `tokenizer = WordTokenizer('kytea')` )
> Non case sensitive

- .travis.yml
- README.md
- setup.py
- tests/test_word_tokenize.py
- tiny_tokenizer/__init__.py
- tiny_tokenizer/word_tokenizer.py
I introduce the environment variable to enable only the sentence tokenizer by the following command.
`TINY_TOKENIZER_BUILD_WORD_TOKENIZER=0 pip install tiny_tokenizer`
issue: https://github.com/himkt/tiny_tokenizer/issues/14
> Add option ignoring word

- example/tokenize_demo.py
- setup.py
- tests/test_word_tokenize.py
- tiny_tokenizer/__init__.py
- tiny_tokenizer/word_tokenizer.py
I introduce the class `Token` such that we can see part-of-speech tags of parsed results.
```python
tokenizer = WordTokenizer(tokenizer="MeCab", with_postag=True)
print(tokenizer.tokenize(sentence))  # -> `我輩 (名詞), は (助詞), 猫 (名詞), で (助動詞), ある (助動詞), 。 (記号)`
```
> Add token class

- example/tokenize_demo.py
- tiny_tokenizer/word_tokenizer.py
In the current implementation, tiny_tokenizer fails when the following input is given.
```
input: '東京特許許可局（とうきょうとっきょきょかきょく） 日本語の早口言葉。'
output: '...かきょく/名詞/かきょく ）/補助記号/） /補助記号/UNK 日本/名詞/にっぽん 語/名詞/ご...'
^^^
```
Double-space breaks WordTokenizer
> Fix bug when kytea tokenizer encounter UNK word

- tests/test_token.py
- tiny_tokenizer/tiny_tokenizer_token.py
ref. https://github.com/himkt/tiny_tokenizer/issues/29
> Add attributes to token

- example/tokenize_demo.py
85e05e6 fixed import path
16bba8a
When this script is executed in an environment where a specific tokenizer does not exist, `OSError` or `RuntimeError` for tokenizer using `kytea` or `sentencepiece` and `KeyError` for tokenizer using `Sudachi` occurs because there is no `/ user/local/share/kytea/model.bin` etc. before `ModuleNotFoundError`.
> fix some bugs at tokenize_demo.py

- .travis.yml
I create a job to test tiny_tokenizer where there is no external tokenizer library available.
> Add CI job without external libraries

- tests/test_token.py
- tests/word_tokenizer/test_postagging.py
- tiny_tokenizer/tiny_tokenizer_token.py
- tiny_tokenizer/word_tokenizers/kytea_tokenizer.py
- tiny_tokenizer/word_tokenizers/mecab_tokenizer.py
- tiny_tokenizer/word_tokenizers/sudachi_tokenizer.py
This PR introduces supports detailed token attributes such as:
- postag1, postag2, postag3: mecab, sudachi
- inflection, conjugation: mecab, sudachi
- origin_form: mecab, sudachi
- yomi: mecab, sudachi
- pronunciation: mecab, kytea
- normalized_form: sudachipy
> Support token detailed attr

- tiny_tokenizer/word_tokenizer.py
- tiny_tokenizer/word_tokenizers/mecab_tokenizer.py
This PR introduces MeCab system dictionary support.
Users can specify their own system dictionaries by following.
```python
WordTokenizer("mecab", system_dictionary_path="...")
```
And, this PR breaks compatibilities.
```python
WordTokenizer("mecab", dictionary_path="...")
```
should be
```python
WordTokenizer("mecab", user_dictionary_path="...")
```
> Support system dictionary in MeCab

- Dockerfile
- docker-compose.yml
- konoha/api/server.py
- konoha/api/tokenizers.py
- poetry.lock
- pyproject.toml
This PR introduces a demonstration server for word tokenization powered by FastAPI.
There are available several tokenizers (`mecab`, `janome`, `kytea`, `sentencepiece`, 
`sudachi`, `whitespace`, `character`) for a choice.
Tokenization is done by posting a json object to `localhost:8000/api/tokenize`.
You can also batch tokenize by passing `texts: ["１つ目の入力", "２つ目の入力"]` to the server.
You can see documentation in `localhost:8000/redoc`.
> Add tokenization server.

- Dockerfile
- README.md
- docker-compose.yml
- poetry.lock
- pyproject.toml
The current implementation makes users install a dictionary for `SudachiPy` manually.
This PR adds `sudachidict_core` to a dependency, which means users are able to use `konoha` with `SudachiPy` by simply running `pip install konoha[sudachi]`, `pip install konoha[all]` or `pip install konoha[all_with_integrations]`.
> Install `sudachidict_core` in `pip install`.

- tests/word_tokenizer/test_kytea_tokenizer.py
- tests/word_tokenizer/test_sentencepiece_tokenizer.py
ref. https://github.com/himkt/konoha/pull/107#discussion_r466123751
CI is not able to access AWS credentials if the PR comes from forked repo.
> Skip tests using boto3 if AWS credentials are not found

- konoha/sentence_tokenizer.py
@hppRC show that a sentence tokenizer could be faster by using pre-compiled regexp objects.
In this PR, I modified `sentence_tokenizer.py` based on the suggestion by @hppRC.
The following benchmark confirms the certain performance gain.
```bash
> time poetry run python benchmark.py
mean: 8.069960498809815sec with std 0.2850634093193728
poetry run python benchmark.py  41.41s user 0.34s system 102% cpu 40.931 total
> git checkout performance/sentence-tokenization
Switched to branch 'performance/sentence-tokenization'
> time poetry run python benchmark.py
mean: 7.03724775314331sec with std 0.1719490321050499
poetry run python benchmark.py  36.23s user 0.35s system 102% cpu 35.836 total
```
- benchmark script:
<details>
```python
from konoha import SentenceTokenizer
import time
import numpy …
```
> Run pre-compile regular expressions before tokenization

- konoha/integrations/allennlp.py
- poetry.lock
- pyproject.toml
- test_fixtures/classifier_v1.jsonnet
- tests/integrations/test_allennlp_integration.py
Resolve https://github.com/himkt/konoha/issues/115.
From AllenNLP v1.3.0, a path to AllenNLP token class is located in `allennlp.data.tokenizers.token_class`.
This PR updates a konoha integration for AllenNLP to follow this change.
(ref. https://github.com/allenai/allennlp/releases/tag/v1.3.0)
> Support AllenNLP>=1.3.0 by renaming path to Token class

- pyproject.toml
- setup.cfg
- c4a98b5 b3c6048: Allow us to write a line up to 119 chars in one line
- 00deb3f: Remove `poetry-dynamic-versioning.substitution`, which is not used
> Update max-line-length for linters and remove poetry-dynamic-versioning.substitution

- .github/workflows/pythonpackage.yml
- README.md
- docker/app/Dockerfile
- konoha/api/server.py
- konoha/api/v1/tokenization.py
- libexec/api.py
- tests/api/v1/test_tokenization.py
- eb729b0 **breaking change**: changes a path to tokenization API
- cf2b258 upgrades Ubuntu from 18.04 to 20.04
- ac82176 511117b update api stuff
- c2398d5 adds tests
- 2e3df8d updates Dockerfile
- 0fd6aea cleans up GitHub Actions configuration
- 8a97686 updates README to remove a note for nagisa installation
> Update API module: change endpoint path and upgrade Ubuntu to 20.04

- konoha/__init__.py
- konoha/api/v1/tokenization.py
- konoha/data/token.py
- konoha/integrations/_allennlp.py
- konoha/integrations/allennlp.py
- konoha/sentence_tokenizer.py
- konoha/word_tokenizer.py
- konoha/word_tokenizers/janome_tokenizer.py
- konoha/word_tokenizers/kytea_tokenizer.py
- konoha/word_tokenizers/mecab_tokenizer.py
- konoha/word_tokenizers/nagisa_tokenizer.py
- konoha/word_tokenizers/sudachi_tokenizer.py
- tests/api/v1/test_tokenization.py
- tests/word_tokenizer/test_remote_tokenizer.py
This PR modifies the API server to contain rich token information in a response.
> % curl localhost:8000/api/v1/tokenize -X POST -H "Content-Type: application/json" -d '{"tokenizer": "sudachi", "text": "自然言語処理", "with_postag": true}'| jq
```json
{
"tokens": [
[
{
"surface": "自然",
"postag": "名詞",
"postag2": "普通名詞",
"postag3": "一般",
"postag4": "*",
"inflection": "*",
"conjugation": "*",
"base_form": "自然",
"yomi": "シゼン",
"pron": null,
"normalized_form": "自然"
},
{
"surface": "言語",
"postag": "名詞",
"postag2": "普通名詞",
"postag3": "一般",
"postag4": "*",
"inflection": "*",
"conjugation": "*",
"base_form": "言語",
"yomi": "ゲンゴ",
"pron": null,
"normalized_form": "言語"
},
{
"surface": "処理",
"postag": "名詞",
"postag2": "普通名詞",
"postag3": "サ変可能",
"postag4": "*",
"inflection": "*",
"conjugation": "*", …
```
> Return detailed information of token in konoha API

- docker/app/Dockerfile
- libexec/api.py
- poetry.lock
- pyproject.toml
ref. https://github.com/encode/uvicorn/pull/875
From `uvicorn==v0.13.0`, we can launch uvicorn with factory-style imports.
This means we can remove the `libexec` directory.
> Use `--factory` to launch app server with factory-style imports

- poetry.lock
- pyproject.toml
- test_fixtures/classifier.jsonnet
- tests/integrations/test_allennlp_integration.py
This PR updates a dependency for AllenNLP.
After being merged, konoha support AllenNLP v2.
> Upgrade dependency for AllenNLP

- konoha/word_tokenizer.py
- tests/test_word_tokenizer.py
<details>
```python
from typing import Dict
from konoha import WordTokenizer
import pytest
import json
@pytest.mark.parametrize(
"tokenizer_params", [
{"tokenizer": "mecab"},
{"tokenizer": "mecab", "with_postag": True},
{"tokenizer": "sudachi", "mode": "A"},
{"tokenizer": "sudachi", "mode": "A", "with_postag": True},
{"tokenizer": "kytea"},
{"tokenizer": "kytea", "with_postag": True},
{"tokenizer": "nagisa"},
{"tokenizer": "nagisa", "with_postag": True},
{"tokenizer": "janome"},
{"tokenizer": "janome", "with_postag": True},
{"tokenizer": "character"},
{"tokenizer": "whitespace"},
{"tokenizer": "sentencepiece", "model_path": "data/model.spm"},
]
)
def test_tokenization(tokenizer_params: Dict):
texts = ["吾輩は猫である", "あなたは私です"]
tokenizer = WordTokenizer(**tokenizer_params)
tokenizer_name = …
```
> Extract batch tokenization from WordTokenizer.tokenize

- konoha/api/v1/batch_tokenization.py
- konoha/api/v1/tokenization.py
I found that sometimes konoha api failed to tokenize when handling multiple accesses.
This may be caused by resource competition because of the cached tokenizer shared with each access. 
By using async methods, this problem will be resolved since each access are scheduled by event loop and not executed simultaneously.
> Use async methods to avoid resource competition

- README.md
- konoha/sentence_tokenizer.py
- tests/test_sentence_tokenizer.py
This PR introduces two parameters `patterns` and `period` to make sentence tokenization configurable.
If these parameters are not given by users, the behavior doesn't change from previous versions of konoha.
```python
tokenizer = SentenceTokenizer(
patterns=SentenceTokenizer.PATTERNS + [re.compile(r"『.*?』")],
)
document = "わんわん。「にゃ？」(にゃー）わんわん。『わおーん。』（犬より。）"
expect = ["わんわん。", "「にゃ？」(にゃー）わんわん。", "『わおーん。』（犬より。）"]
result = corpus.tokenize(DOCUMENT5)
assert expect == result
```
```python
tokenizer = SentenceTokenizer(period="．")
document = "わんわん。「にゃ？」(にゃー）わんわん．「わおーん。」（犬より。）"
expect = ["わんわん。「にゃ？」(にゃー）わんわん．", "「わおーん。」（犬より。）"]
result = corpus.tokenize(DOCUMENT5)
assert expect == result
```
Thank you so much @hppRC for the insight!
> Configurable sentence tokenizer

- .github/workflows/publish.yml
This PR introduces a workflow to automatically publish the package using poetry-publish.
https://github.com/marketplace/actions/publish-python-poetry-package
> Add workflow to publish

- poetry.lock
- pyproject.toml
> This repository is for 0.5.* version of SudachiPy, 0.6* and above are developed as [Sudachi.rs](https://github.com/WorksApplications/sudachi.rs).
https://github.com/WorksApplications/SudachiPy
> deps: use newer sudachipy

- src/konoha/api/v1/batch_tokenization.py
- src/konoha/api/v1/tokenization.py
In pytest outputs, there are warnings like below.
I removed two `pydantic` deprecation warning by replacing `dict` with `model_dump`.
ref: https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump
```
=============================== warnings summary ===============================
tests/api/v1/test_batch_tokenization.py: 10 warnings
/home/runner/work/konoha/konoha/src/konoha/api/v1/batch_tokenization.py:29: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
params = params.dict(exclude={"text", "texts"})
tests/api/v1/test_batch_tokenization.py::test_tokenization[tokenizer_params7] …
```
> remove pydantic deprecation warning
